### ISSUE TITLE
Inconsistencies due to omemo.top references to closed issues

### ISSUE THREAD

**Issue by cyBea** [bascht/omemo-top#182]
Some issues referenced by omemo.top to track omemo progress of clients are closed while progressbar is not 100%
ex: https://github.com/dino/dino/issues/36
ex: https://github.com/ChatSecure/ChatSecure-iOS/issues/376

What has to be done about this? Reference other issues? Implement  #122?

(btw: https://en.wikipedia.org/wiki/Comparison_of_instant_messaging_clients#XMPP-related_features claims omemo support of chatsecure)

**Comment by evaryont** [comment]
The website's progress bars are not dynamic. They are judgement calls by people. If you want to, you could submit a PR to update the website to reflect the current status.

**Comment by palbr** [comment]
Trying to determine the OMEM-state of ChatSecure, I reached this issue.

Especially for ChatSecure there have been many discussions in the past:
* #70 
* #74 
* #80 

So the current state of ChatSecure seems to be unclear. Unfortunately, I only have Android phones, so I can't test ChatSecure for myself.

Nevertheless, I wanted to add this comment, since I was close to open another issue "ChatSecure is not marked as 100%, but the ChatSecure release logs claim to be".

**Comment by Echolon** [comment]
@cyBea I will close this. Changes can be made via PRs!
