### ISSUE TITLE
Miranda NG OMEMO not working!

### ISSUE THREAD

**Issue by RIS2000** [bascht/omemo-top#187]
Hello!
Miranda NG OMEMO is not in working state for today, so your site is misinforming people

**Comment by Echolon** [comment]
@RIS2000 Please make a PR with reasonable description.

**Comment by Neustradamus** [comment]
@RIS2000: Have you informed team?
- https://github.com/miranda-ng/miranda-ng/issues?q=is%3Aissue+omemo+

**Comment by Neustradamus** [comment]
@sss123next, @dartraiden, @georgehazan: Please look here and the PR too.

**Comment by Echolon** [comment]
Dear Miranda team,

please apologize for the mentionings, this is not how we propagate issues and it is also not coming from the maintainers. Please excuse.

**Comment by Neustradamus** [comment]
@Echolon: Do not mix XSF and other places.
I know the Miranda NG team. Thanks.

**Comment by dartraiden** [comment]
> Miranda NG OMEMO is not in working state

Miranda NG OMEMP is working between Miranda<->Miranda, but not between Miranda<->some other client.

I do [some test](https://github.com/miranda-ng/miranda-ng/issues/3013)s, but I'm not a coder.

**Comment by sss123next** [comment]
i see issue, as discussed already many times omemo depends on pubsub/pep which working randomly on many servers, for example ejabberd have events to offline offloading turned on by default (which causing omemo to not work properly if no active discovery hacks implemented), in miranda-ng i strictly followed xep (version available at time of implementation), and it is using discovery only by pubsub/pep events, i have looked at other implementations (gajim and some other client, do not remember which one exactly), and they have active discovery implemented (not followed omemo xep), i have talked to xep author, and he said what i must follow xep, so this problematic discovery is expected behavior.

anyway, i will look at more data related to this problem, if it will be provided.

**Comment by Neustradamus** [comment]
@sss123next: maybe you can publish the problem here:
- https://github.com/processone/ejabberd

I am not sure that there is already a ticket.

Normally Miranda NG supports XEP-0384: OMEMO Encryption version 0.3.0:
- https://xmpp.org/extensions/attic/xep-0384-0.3.0.html
- https://xmpp.org/extensions/xep-0384.html

**Comment by sss123next** [comment]
this is not problem in ejabberd itself, but incorrect configuration, or more precisely not suitable for omemo, this options is configurable in ejabberd (i am talking about ejabberd because i am using it for my needs, probably other servers have similar problems).

as for omemo problem in miranda, as i see during last years namespace name in xep changed few more times, we still using old (initial) name in miranda, it may be source of problem, unfortunately different namespace incompatible with each other,  i guess it is possible to implement all namespaces described in xep at once, but it will multiply already large amount of data on server side and add unnecessary complexity ....
