### ISSUE TITLE
Add libpurple-omemo-plugin, address Finch

### ISSUE THREAD

**Issue by Kagami** [bascht/omemo-top#29]
I don't know how to properly put it on the list, so creating issue instead.

There is another OMEMO plugin for Pidgin, [libpurple-omemo-plugin](https://git.imp.fu-berlin.de/mancho/libpurple-omemo-plugin). Judging by description, it seems to be less stable than lurch, but probably will be improved too.
Also, it seems like at least lurch works in Finch too, not sure about libpurple-omemo-plugin.

**Comment by bascht** [comment]
With #36 I moved and restructured the data quite a bit, so now we could e.g. have custom properties like a foldable info button that expands the table row, so we could display that info. :)

**Comment by bascht** [comment]
See also: #40

**Comment by oodbur** [comment]
separate report for Finch: #57

**Comment by bascht** [comment]
@Kagami Is this something that can be covered by the changes in #40?

**Comment by Kagami** [comment]
Yea, looks nice :+1: 
Or maybe libpurple-omemo-plugin should go to `Alternative OMEMO Plugins` section instead. It haven't been updated for 10 months, probably not maintained.

**Comment by Echolon** [comment]
@Kagami 

you you mind to create a PR on this? That yould be great!

**Comment by butyoutried** [comment]
I'm still hunting no longer relevant issues :)

There's also nothing to change. libpurple-omemo-plugin already exists in the Alternative OMEMO Plugins section as suggested. BTW, plugin is [barely updated](https://github.com/manchito/libpurple-omemo-plugin/commits/master) since 2017.

And Finch has it's own [bug report.](https://github.com/bascht/omemo-top/issues/57)

**Comment by bascht** [comment]
@butyoutried much appreciated. Thanks for digging through all the open issues! :sunflower:
