### ISSUE TITLE
Add "won't happen" indicator

### ISSUE THREAD

**Issue by vanitasvitae** [bascht/omemo-top#83]
Some apps are highly unlikely to get OMEMO support anytime soon (see for example https://github.com/redsolution/xabber-android/issues/540).

It would be nice to have a visual indicator that tells the user that OMEMO is not going to be implemented at all. This would prevent devs from getting spammed from user requests for that feature.

**Comment by jumpwe-movim-eu** [comment]
Preventing motivation seems imprudent

**Comment by Flowdalic** [comment]
As far as I understood the Xabber folks, their stance is not "won't happen" more like "not our focus". They said clearly that if someone would either donate the code or money for the development, they wouldn't reject it unconditional.

So maybe instead of "won't happen", create a "not a goal, but donations welcome" indicator?

**Comment by vanitasvitae** [comment]
By the time I created this issue, it seamed, like they were annoyed by people requesting OMEMO as a feature, that's why I created this request.

**Comment by lostinlight** [comment]
Depending on how things work out, Movim might need an [update](https://github.com/movim/movim/issues/63). Right now the progress bar makes it feel like "under development", seems not realistic.

**Comment by evaryont** [comment]
Whoops, this ticket has been left languishing. It should probably be closed given that my PR has been merged in.

**Comment by bascht** [comment]
@evaryont Yup, you're right. Thanks for the hint.
